org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric для Minecraft 1.20.1
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
fabric_version=0.92.2+1.20.1

# Библиотека 3D-брони (Modrinth, MIT)
armor_model_api_version=1.0.0+1.20.1-fabric

# Мод
mod_version=1.0.0
maven_group=com.bleid.vestments
archives_base_name=vestments
